name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      # Top languages
      - name: Generate top languages card (dark mode)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=6&exclude_repo=nardusmollentze.com&hide=tex&theme=dark
          path: cards/top-langs-dark.svg
          token: ${{ secrets.PAT }}

      - name: Generate top languages card (light mode)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=6&exclude_repo=nardusmollentze.com&hide=tex&theme=default
          path: cards/top-langs-light.svg
          token: ${{ secrets.PAT }}

      # Pinned repos
      # - ACE2
      - name: Generate pin card - ace2 (dark mode)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=ace2&theme=dark
          path: cards/pin-ace2-dark.svg
          token: ${{ secrets.PAT }}

      - name: Generate pin card - ace2 (light mode)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=ace2&theme=default
          path: cards/pin-ace2-light.svg
          token: ${{ secrets.PAT }}

      # - zoonotic_rank
      - name: Generate pin card - zoonotic_rank (dark mode)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=zoonotic_rank&theme=dark
          path: cards/pin-zoonotic_rank-dark.svg
          token: ${{ secrets.PAT }}

      - name: Generate pin card - zoonotic_rank (light mode)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=zoonotic_rank&theme=default
          path: cards/pin-zoonotic_rank-light.svg
          token: ${{ secrets.PAT }}

      # - hiv_growth_rates
      - name: Generate pin card - hiv_growth_rates (dark mode)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=hiv_growth_rates&theme=dark
          path: cards/pin-hiv_growth_rates-dark.svg
          token: ${{ secrets.PAT }}

      - name: Generate pin card - hiv_growth_rates (light mode)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=hiv_growth_rates&theme=default
          path: cards/pin-hiv_growth_rates-light.svg
          token: ${{ secrets.PAT }}

      # - isg_composition
      - name: Generate pin card - isg_composition (dark mode)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=isg_composition&theme=dark
          path: cards/pin-isg_composition-dark.svg
          token: ${{ secrets.PAT }}

      - name: Generate pin card - isg_composition (light mode)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=isg_composition&theme=default
          path: cards/pin-isg_composition-light.svg
          token: ${{ secrets.PAT }}

      # Commit
      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add cards/*.svg
          git commit -m "Update README cards" || exit 0
          git push
